name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'Jacob-Roberts' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: write # To push changes back to the repository
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn

      # This step will run changeset version, setting the step output to if there were changesets found
      - name: Version command
        id: version
        run: |
          echo ::set-output name=changes::$(npx changeset version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')

      - name: Release packages
        if: steps.version.outputs.changes == 'true'
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Use OIDC for npm authentication instead of NPM_TOKEN
          NPM_TOKEN: "" # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868

      - name: Push changes
        if: steps.version.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Action"
          git add -A
          git commit -m "New version" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
